### ISSUE TITLE
Fingerpring/Biometric Unlock not available on Pixel 8 / Disable Anti Uninstall

### ISSUE THREAD

**Issue by Montiburn213** [aload0/AppLock#12]
Hi there.

First of all thanks for that App. Great Job.

I can't select Biometric Unlock in the settings. It's grayed out on my Pixel 8 with Android 15. How can I fix this?

Second question: Where can I disable the anti-uninstall feature? After entering the PIN, I get a message saying I can disable the admin permission again, but I can't see where. If I click on it again, it's reactivated.

THX

![Image](https://github.com/user-attachments/assets/0a838ede-86c9-4d44-8532-857033385447)

**Comment by PranavPurwar** [comment]
You can disable it from `Settings > Apps > Special Access > Device Admin Apps > App Lock` Disable it from there.

For the fingerprint issue, can you check if this build solves the issue? https://github.com/PranavPurwar/AppLock/raw/refs/heads/master/app/release/app-release.apk

And Thanks for trying the app!

**Comment by Montiburn213** [comment]
Thanks. Tested it but same issue. Grayed out.

**Comment by PranavPurwar** [comment]
Should be fixed now. I had forgotten to change the requirement in settings. The same link above would point to the fixed build

**Comment by Montiburn213** [comment]
Sadly no. Still grayed out

**Comment by PranavPurwar** [comment]
> Sadly no. Still grayed out

Does it work on the new IzzyOnDroid release?

**Comment by PranavPurwar** [comment]
> Sadly no. Still grayed out

Have you enabled fingerprint as an authentication option for your device unlock settings? That is needed to use the feature as the biometrics are checked by system

**Comment by Montiburn213** [comment]
Yes, thats how I unlock my Device.

Still not available :( Tried the izzy one as well

Thx for your help. I'm done trying.
