### ISSUE TITLE
Inner-app links of locked app open the home screen of the app

### ISSUE THREAD

**Issue by Satanarious** [aload0/AppLock#8]
Whenever a inner-link to a locked app is opened it shows the lock screen and upon unlock, opens the home screen of the app instead of opening the actual link or the activity in the app.

e.g. Lets take google photos as the locked app here. If I have an app that opens google photos to select images to add to it, then upon unlocking google photos, the home screen of google photos is opened instead of the image selection screen.

Edit: I recently noticed that pressing back from the home screen would take you to the link. Which means the home screen is just opening after app unlock, no matter what link is being opened

**Comment by PranavPurwar** [comment]
fixed in https://github.com/PranavPurwar/AppLock/raw/refs/heads/master/app/release/app-release.apk

**Comment by Satanarious** [comment]
Seems to be fixed with this, but the lock screen shows again after the app is exited, in my case google photos, when I was using telegram and didn't show at all when I was using github. And suddenly I found the app lock not working for all apps as soon as I closed the app link 1-2 times. I started facing #4 again after this and it was working well for 5 days.

**Comment by Satanarious** [comment]
Working fine after 10 days of usage. Closing this.

**Comment by Satanarious** [comment]
This issue persists in Usage Statistics and Shizuku Service.

**Comment by PranavPurwar** [comment]
Try v2.2.0, if the issue persists, reopen this issue.
